# Generated by Django 5.2.6 on 2025-09-07 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_nonschoolday'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='attendancesessionrecord',
            name='idx_asr_enr_date',
        ),
        migrations.RemoveIndex(
            model_name='attendancesessionrecord',
            name='idx_asr_date_sess',
        ),
        migrations.RemoveIndex(
            model_name='attendancesessionrecord',
            name='idx_asr_date',
        ),
    ]
