# Generated by Django 5.2.6 on 2025-09-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_remove_attendancesessionrecord_idx_asr_enr_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_phone',
            field=models.CharField(blank=True, help_text='Parent/guardian mobile (e.g., 09171234567 or +639171234567)', max_length=30),
        ),
    ]
