# Generated by Django 5.1.2 on 2025-09-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_messagingconfig_parentmessagelog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='parentmessagelog',
            new_name='attendance__date_be6e08_idx',
            old_name='idx_pml_date_sess',
        ),
        migrations.RenameIndex(
            model_name='parentmessagelog',
            new_name='attendance__phone_7f4130_idx',
            old_name='idx_pml_phone',
        ),
        migrations.AlterField(
            model_name='messagingconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='parentmessagelog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
