# Generated by Django 5.1.2 on 2025-09-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_merge_0013s'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessagingConfig',
        ),
        migrations.AlterField(
            model_name='attendanceperiodrecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='period',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='ParentMessageLog',
        ),
    ]
