# Generated by Django 5.1.2 on 2025-09-09 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_featureaccess'),
        ('attendance', '0015_remove_legacy_messaging_models'),
    ]

    operations = [
    ]
